# Generated by Django 5.1.4 on 2024-12-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
    ]
