# Generated by Django 5.1.4 on 2024-12-24 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribeapp', '0002_subscription_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='created_at',
        ),
    ]
