# Generated by Django 5.1.4 on 2024-12-23 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_project_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='writer',
        ),
    ]
