# Generated by Django 5.1.4 on 2024-12-24 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0007_article_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comment_count',
        ),
    ]
